version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      #network.publish_host: _eth0_
    networks:
      - elk
      #qnet-static-eth1:
      #  ipv4_address: 192.168.30.131
    #deploy:
    #  mode: replicated
    #   replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    ports:
      - "5044:5044"
      - "5050:5000"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
      #qnet-static-eth1:
      #  ipv4_address: 192.168.30.132
    #deploy:
    #  mode: replicated
    #  replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
      #qnet-static-eth1:
      #  ipv4_address: 192.168.30.133
    #deploy:
    #  mode: replicated
    #  replicas: 1

configs:

  elastic_config:
    file: /share/Container/mounts/elk/elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: /share/Container/mounts/elk/logstash/config/logstash.yml
  logstash_pipeline:
    file: /share/Container/mounts/elk/logstash/pipeline/logstash.conf
  kibana_config:
    file: /share/Container/mounts/elk/kibana/config/kibana.yml

networks:
  elk:
    driver: bridge
  #qnet-static-eth1:
  #  external: true
    #driver: qnet
    #ipam:
    #  driver: qnet
    #  options:
    #    iface: "eth1"
    #  config:
    #    - subnet: 192.168.30.0/24
    #      gateway: 192.168.30.1
